### ISSUE TITLE
To define and identify the influential users in the system 

### ISSUE THREAD

**Issue by abhicodebase** [amyxzhang/wikum#96] opened 2017-11-06 18:32 UTC
Issue

As a developer who is going to collaborate in the improvement of WIKUM source code, I found that WIKUM
 has the potential to identify the influential commentators .

Proposal
To define what influential users means in this context  and how to identify them 

Outcome

- Definition of influential user 
- identification technique algorthms

Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by amyxzhang** [comment] 2017-11-06 18:45
I currently find this issue a little bit vague... What do you think is the intended use case of identifying influential commenters? Why do we wish to know this information and how will we use it?

**Comment by julioremo** [comment] 2017-11-06 18:51
I think this is an example where we could introduce the human in the loop: a down and up-voting button, instead of using NLP.
A user with many up-voted interventions is influential. Further (automatised) decisions can be taken upon this influence rank, i.e. to promote edits by influential users

**Comment by julioremo** [comment] 2017-11-06 18:59
Possible duplicate of https://github.com/amyxzhang/wikum/issues/92 ?

**Comment by abhicodebase** [comment] 2017-11-06 19:00
A lot will depend on how we define an 'influential user' in this context. In Recommender Systems and Marketing domains , "influential users" , are often given some additional incentives to continue to use the system , often in different ways. 
Yes,  they are potential manipulators too.

**Comment by amyxzhang** [comment] 2017-11-06 19:00
I think this was originally about influential commenters. If we use something like Reddit or Disqus data, Wikum does already bring in upvote count and karma, etc. We display upvotes of the comment only in the page.

But you could imagine like - hover over the username and see a box with their influence number, provided by the original data.

**Comment by abhicodebase** [comment] 2017-11-06 21:16
Yes Amy , it was about influential commentators . #92 is probably about summarizers.

**Comment by abhicodebase** [comment] 2017-11-13 11:33
Final report is documented at - https://docs.google.com/document/d/1xdY7avyIxewAcj17ZX-_wPGVGPXt73F0wjLNe6WdHSo/edit?usp=sharing

**Closed** 2017-11-13 11:34 UTC
Labels: AI
